[variables]
main_domain = "${domain}"

[config]
mounts = []

[[config.domains]]
serviceName = "macos"
port = 8_006
host = "${main_domain}"

[config.env]
VERSION = "15"
DISK_SIZE = "64G"
RAM_SIZE = "4G"
CPU_CORES = "2"
