[variables]
main_domain = "${domain}"
calcom_encryption_key = "${base64:32}"
nextauth_secret = "${base64:32}"

[config]
env = [
  "CALCOM_HOST=${main_domain}",
  "NEXTAUTH_SECRET=${nextauth_secret}",
  "CALENDSO_ENCRYPTION_KEY=${calcom_encryption_key}",
]
mounts = []

[[config.domains]]
serviceName = "calcom"
port = 3_000
host = "${main_domain}"
