[variables]
main_domain = "${domain}"
mysql_password = "${password}"
mysql_root_password = "${password}"
admin_password = "${password}"

[config]
mounts = []

[[config.domains]]
serviceName = "yourls-app"
port = 80
host = "${main_domain}"

[config.env]
YOURLS_HOST = "${main_domain}"
YOURLS_ADMIN_USER = "admin"
YOURLS_ADMIN_PASSWORD = "${admin_password}"
MYSQL_PASSWORD = "${mysql_password}"
MYSQL_ROOT_PASSWORD = "${mysql_root_password}"
