[variables]
main_domain = "${domain}"
postgres_password = "${password}"

[[config.domains]]
serviceName = "windmill-caddy"
port = 80
host = "${main_domain}"

[config.env]
WINDMILL_HOST = "${main_domain}"
POSTGRES_PASSWORD = "${postgres_password}"
DATABASE_URL = "postgres://postgres:${postgres_password}@windmill-postgres/windmill?sslmode=disable"

[[config.mounts]]
filePath = "Caddyfile"
content = """
:80 {
    bind 0.0.0.0
    reverse_proxy /ws/* http://windmill-lsp:3001
    reverse_proxy /* http://windmill-server:8000
} 
"""
