[variables]
main_domain = "${domain}"
db_password = "${password}"
db_user = "twenty"
app_secret = "${base64:32}"

[config]
mounts = []

[[config.domains]]
serviceName = "twenty-server"
port = 3_000
host = "${main_domain}"

[config.env]
TWENTY_HOST = "${main_domain}"
DB_USER = "${db_user}"
DB_PASSWORD = "${db_password}"
APP_SECRET = "${app_secret}"
