[variables]
main_domain = "${domain}"

[config]
env = [
  "PUID=1000",
  "PGID=1000",
  "TZ=Etc/UTC",
  "SUBFOLDER=/",
  "NVIDIA_VISIBLE_DEVICES=all",
  "NVIDIA_DRIVER_CAPABILITIES=all",
]
mounts = []

[[config.domains]]
serviceName = "blender"
port = 3_000
host = "${main_domain}"
