[variables]
main_domain = "${domain}"
db_password = "${password:16}"

[config]
[[config.domains]]
serviceName = "bytebase"
port = 8080
host = "${main_domain}"

[config.env]
DB_PASSWORD = "${db_password}" 