[variables]
main_domain = "${domain}"
postgres_password = "${password}"
redis_password = "${password}"

[config]
env = [
  "DISCOURSE_HOST=${main_domain}",
  "POSTGRES_PASSWORD=${postgres_password}",
  "REDIS_PASSWORD=${redis_password}",
]
mounts = []

[[config.domains]]
serviceName = "discourse-app"
port = 3_000
host = "${main_domain}"
