version: "3.8"
services:
  ampache:
    image: ampache/ampache:latest
    restart: unless-stopped
    ports:
      - 80
    volumes:
      - config:/var/www/config
      - log:/var/log/ampache
      - mysql:/var/lib/mysql
      - ${MEDIA_PATH}:/media

volumes:
  config: {}
  log: {}
  mysql: {} 