[variables]
main_domain = "${domain}"

[config]
mounts = []

[[config.domains]]
serviceName = "open-webui"
port = 8_080
host = "${main_domain}"

[config.env]
OLLAMA_DOCKER_TAG = "0.1.47"
WEBUI_DOCKER_TAG = "0.3.7"
