[variables]
main_domain = "${domain}"
db_password = "${password}"
db_username = "langflow"

[config]
mounts = []

[[config.domains]]
serviceName = "langflow"
port = 7_860
host = "${main_domain}"

[config.env]
DB_PASSWORD = "${db_password}"
DB_USERNAME = "${db_username}"
