version: "3.8"
services:
  pocketbase:
    image: spectado/pocketbase:0.23.3
    restart: unless-stopped
    volumes:
      - /etc/Deployit/templates/${HASH}/data:/pb_data
      - /etc/Deployit/templates/${HASH}/public:/pb_public
      - /etc/Deployit/templates/${HASH}/migrations:/pb_migrations
