version: "3"

services:
  chromium:
    image: lscr.io/linuxserver/chromium:5f5dd27e-ls102
    ports:
      - "3000"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
    volumes:
      - config:/config

volumes:
  config: 