[variables]
main_domain = "${domain}"
pg_pass = "${password}"

[config]
mounts = []

env = [
"# Create .env from this example file and replace values for the environment.",
"# The application expects a separate .env.test for test environment configuration",
"# Get detailed information about each variable here: https://docs.tooljet.com/docs/setup/env-vars",
"",
"TOOLJET_HOST=http://${main_domain}:80",
"TOOLJET_HTTP_PROXY=http://${main_domain}:80",
"LOCKBOX_MASTER_KEY=${password:32}",
"SECRET_KEY_BASE=${password:64}",
"",
"# DATABASE CONFIG",
"ORM_LOGGING=all",
"PG_DB=tooljet_production",
"PG_USER=postgres",
"PG_HOST=postgres",
"PG_PASS=${pg_pass}",
"",
"# The above postgres values is set to its default state. If necessary, kindly modify it according to your personal preference.",
"",
"# TOOLJET DATABASE",
"TOOLJET_DB=tooljet_db",
"TOOLJET_DB_USER=postgres",
"TOOLJET_DB_HOST=postgres",
"TOOLJET_DB_PASS=${pg_pass}",
"",
"PGRST_DB_URI=postgres://postgres:${pg_pass}@postgres/tooljet_db",
"PGRST_HOST=localhost:3002",
"PGRST_JWT_SECRET=${password:32}",
"PGRST_SERVER_PORT=3002",
"",
"# Redis",
"REDIS_HOST=localhost",
"REDIS_PORT=6379",
"REDIS_USER=default",
"REDIS_PASSWORD=",
"",
"# Checks every 24 hours to see if a new version of ToolJet is available",
"# (Enabled by default. Set false to disable)",
"CHECK_FOR_UPDATES=true",
"",
"# Checks every 24 hours to update app telemetry data to ToolJet hub.",
"# (Telemetry is enabled by default. Set value to true to disable.)",
"DISABLE_TOOLJET_TELEMETRY=true",
"",
"GOOGLE_CLIENT_ID=",
"GOOGLE_CLIENT_SECRET=",
"",
"# EMAIL CONFIGURATION",
"DEFAULT_FROM_EMAIL=hello@tooljet.io",
"SMTP_USERNAME=",
"SMTP_PASSWORD=",
"SMTP_DOMAIN=",
"SMTP_PORT=",
"",
"# DISABLE USER SIGNUPS (true or false). only applicable if Multi-Workspace feature is enabled",
"DISABLE_SIGNUPS=",
"",
"# OBSERVABILITY",
"APM_VENDOR=",
"SENTRY_DNS=",
"SENTRY_DEBUG=",
"",
"# FEATURE TOGGLE",
"COMMENT_FEATURE_ENABLE=",
"ENABLE_MULTIPLAYER_EDITING=true",
"ENABLE_MARKETPLACE_FEATURE=true",
"",
"# SSO (Applicable only for Multi-Workspace)",
"SSO_GOOGLE_OAUTH2_CLIENT_ID=",
"SSO_GIT_OAUTH2_CLIENT_ID=",
"SSO_GIT_OAUTH2_CLIENT_SECRET=",
"SSO_GIT_OAUTH2_HOST=",
"SSO_ACCEPTED_DOMAINS=",
"SSO_DISABLE_SIGNUPS=",
"",
"#ONBOARDING",
"ENABLE_ONBOARDING_QUESTIONS_FOR_ALL_SIGN_UPS=",
"",
"#session expiry in minutes",
"USER_SESSION_EXPIRY=2880",
"",
"#TELEMETRY",
"DEPLOYMENT_PLATFORM=docker"
]

[[config.domains]]
serviceName = "tooljet"
port = 80
host = "${main_domain}"