version: "3.8"
services:
  anonupload:
    image: ghcr.io/supernova3339/anonfiles:1
    restart: unless-stopped
    ports:
      - 80
    environment:
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - CONTACT_EMAIL=${CONTACT_EMAIL}
    volumes:
      - uploads:/var/www/html/uploads

volumes:
  uploads: {} 